### ISSUE TITLE
Unresponsive and without custom prompt when debug={false}

### ISSUE THREAD

**Issue by zxpectre** [as-ideas/add-to-homescreen-react#2]
Hi, your component looks very promising!, but for two days now I can't make it work properly.

Only in Firefox and while `debug={true}` I've managed to lauch the dialog with my own `customPromptContent `object as prop. Otherwise dialog keeps unresponsive and only showing default `DEFAULT_PROMPT`.

Is your code working and is there a new suggested way to call the <AddToHomeScreen/> component?

Also when CRA builds my frontend in production this error appears after including your package:

> backend.js:6 Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Any help would be much appreciated.

**Comment by ltparis2018** [comment]
I'm very sorry for the delay. Unfortunately, GitHub's notification of your bug report seems to have gotten lost, so I unfortunately missed it. I apologize for that.
If you still need help with the integration, I will be happy to assist you. 
We use the component ourselves in our applications where it works fine. Therefore I don't have a clue for you immediately what exactly the problem might be.
So it would be helpful if you could send me the code snippet you use to embed the React component. Then I could better analyze the problem.

**Comment by ltparis2018** [comment]
With release 1.0.3 we provide some examples for integration and configuration of the Add-to-Homescreen React component. I hope they are helpful showcases for the most common use cases and can help finding any problems.
If not, please do not hesitate to create a new issue. We will try to react more promptly than last time.
