### ISSUE TITLE
How to test in development

### ISSUE THREAD

**Issue by thuram** [as-ideas/add-to-homescreen-react#6]
Firstly, thank you for create this package! 

I wanna know if is possible test the <AddToHomeScreen /> in development env. Shows this component for validate your styles before push to production.

**Comment by ltparis2018** [comment]
We are currently working on an example for the basic integration of the add-to-homescreen-react component in a frontend project. You can already see the current status on the master branch. The example also shows how you can run the component in the development environment (with the webpack dev server). I hope this helps you.

**Comment by rbuer** [comment]
Just added an [Example section](https://github.com/as-ideas/add-to-homescreen-react#example) to the readme https://github.com/as-ideas/add-to-homescreen-react/commit/bd50dfe59e420d1ecb6fd7be322d808bd57c5bd5
